server:
  port: 8080
spring:
  application:
    name: "CrediYaSolicitudes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:h2:mem:test"
    username: "sa"
    password: "pass"
    driverClassName: "org.h2.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.H2Dialect"
adapter:
  r2dbc-postgresql:
    host: "localhost"
    port: 5433
    database: "CrediYaSolicitudes"
    schema: "public"
    username: "postgres"
    password: 1005076148
  restconsumer:
    timeout: 5000
    url: "http://localhost:8081"

  sqs:
    region: "us-east-2"
    queues:
      loan-application-state-changed: "https://sqs.us-east-2.amazonaws.com/551647579158/queue-loan"
      auto-validate-loan: "https://sqs.us-east-2.amazonaws.com/551647579158/auto-validate-sqs"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
logging:
  level:
    org.springframework.web: "DEBUG"
    io.r2dbc.postgresql: "DEBUG"
    co.com.registeruser: "DEBUG"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"

