app:
  ports:
    - "8080:8080"

spring:
  application:
    name: CrediYaSolicitudes

  r2dbc:
    url: r2dbc:postgresql://db-auth:5432/CrediYaSolicitudes
    username: postgres
    password: 1005076148

  sql:
    init:
      mode: always
      platform: postgres
      schema-locations: classpath:script/database.sql

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

adapter:
  r2dbc-postgresql:
    host: db-loan
    port: 5432
    database: CrediYaSolicitudes
    schema: public
    username: postgres
    password: 1005076148

  restconsumer:
    timeout: 5000
    url: http://authentication-app:8081

  sqs:
    region: "us-east-2"
    queues:
      loan-application-state-changed: "https://sqs.us-east-2.amazonaws.com/551647579158/queue-loan"
      auto-validate-loan: "https://sqs.us-east-2.amazonaws.com/551647579158/auto-validate-sqs"
      review-approved-loan: "https://sqs.us-east-2.amazonaws.com/551647579158/approved-loan-review"

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
